### ISSUE TITLE
README is confusing

### ISSUE THREAD

**Issue by knpwrs** [darkskyapp/binary-search#15]
> Be advised that passing in a comparator function is required. Since you're probably using one for your sort function anyway, this isn't a big deal.

This implies, to me anyway, that a sorting comparator is expected. However, if we look at the actual [usage](https://github.com/darkskyapp/binary-search/blob/b930e2589da1c35d85a30f50efe2183fc5c5c92d/index.js#L26) of the passed comparator it looks like the first and second parameters are an object from the haystack and the needle, respectively. This is not the same as a sort comparator.

**Comment by TrevorSayre** [comment]
`Array.prototype.sort()` is used as _arr_.sort(_compareFunction_) where the _compareFunction_ takes two parameters with each being an element from the array. The "comparator function" for binary-search, however, seems to take two parameters with the first being an element from the array and the second being the needle. This is not clear in the README and is really only discovered through usage or reading the source code.

**Comment by ironwallaby** [comment]
Reasonable suggestion. Thanks, and also for correcting it with a PR!
