### ISSUE TITLE
Duplicates in the sorted list - note in README?

### ISSUE THREAD

**Issue by tvedtorama** [darkskyapp/binary-search#21]
I have duplicates in my list and thought for a while that my use of the bs-library was just fine, until I discovered that the duplicates was included semi-randomly.

I guess this is a catch with the algorithm - that you can't be sure that the first element of a given value is returned when there is an exact match.  

Should this be pointed out in the README? In case other ignorant developers comes along?

Note: This might be irrelevant in most cases, but I use the tool to find intervals of two indices. Not realising that there could be more of the same value at the start or end of the interval caused a major bug.

**Comment by ghost** [comment]
Correct, the algorithm's only guarantee is that it returns _an_ index of the requested value, and doesn't care which. I've updated the docs to reflect this. Thanks!
